### ISSUE TITLE
Line 15 in 2_convae.lua

### ISSUE THREAD

**Issue by yinghuixia** [jakezhaojb/StrideAE#1]
I am not sure if I understand your code correctly. Shouldn't the size of input and output be the same? If you use NormSpatialConvolution instead of deconvolution when decoding, would it change the size?

**Comment by jakezhaojb** [comment]
@juju2827 No, it won't. Normalized spatial convolution only has the effect on the scale.

**Comment by yinghuixia** [comment]
Thanks for your reply.  May I ask where I can find the code SoftPooling&SoftUnpooling and myaenn?

**Comment by jakezhaojb** [comment]
@juju2827  I will open source it in a month. Now, you don't necessarily need it. I just modify it and now it gets rid of that module. Thanks!

**Comment by yinghuixia** [comment]
Thanks again. Very helpful. Does it learn meaningful features from cifar? I tried the same setting but the loss function does not converge.
